### ISSUE TITLE
Some files Missing

### ISSUE THREAD

**Issue by varunchandran333** [bonoj/ThirdEye#1]
I have found that some files are missing, its not possible to load in the studio. I am not an expert.so if u found it as my mistake please forgive.
drawable folder and some integer values folder are missing and its not in proper structure that the message comes.

**Comment by bonoj** [comment]
I have a solution for you! I've been meaning to migrate the code out of that old folder, so I force pushed an update to the file structure and hopefully this should clear up any problems. Here goes:

Delete the code you downloaded from my repository.

Delete the app you installed on your phone/emulator.

Clone or download the code again from the Third Eye repository.
(It has changed, the file structure is now different).

Build and run the project!

You will need to create and configure a project with the same package name on the Google Developers Console, enable the Google Places API, create an API key, and place it into your gradle.properties file as described in the README, but the project should still build without it.

Let me know how it goes, Varun!

**Comment by varunchandran333** [comment]
I dont have words to express my feeling, thank you so much for this
wonderful solution.
I was really trying to find a solution like this, which i can learn and
improve myself.
once again thank you a lot.
Will keep in touch with your repo, expecting more from that.

**Comment by varunchandran333** [comment]
I have some doubt like
1)why you used volley other than retrofit?
2)How could we create a base network class on this, where we can just use
them anywhere
I would like  to add places navigation on this?
I f you have time please try to answer this, and if not let it be, no
worries. thanks in advance

**Comment by bonoj** [comment]
My pleasure, Varun! I'm very glad to hear that the clone and build process is much smoother now.

And please, feel free to make any modifications or additions that you like. Currently, users can walk towards their desired location and watch the distance decrease. What do you envision for a places navigation feature? If you submit a pull request, I will happily include improvements and new features!

1) Volley vs. Retrofit:
Retrofit is great, but I'm partial to Volley due to its extensibility and its wonderful caching behavior. Faster and more efficient caching is also why I prefer Glide to Picasso. Here are a few articles to check out:
https://medium.com/@ali.muzaffar/is-retrofit-faster-than-volley-the-answer-may-surprise-you-4379bc589d7c
http://vickychijwani.me/retrofit-vs-volley/

2) Can you clarify what you mean by base network class? If you mean to decouple Volley from the OverlayActivity and PlaceDetailsActivity and create a class that supports both Volley and Retrofit, I think that's a fantastic idea!

**Comment by varunchandran333** [comment]
Its fine, i am not much aware of volley, i am also a new developer.
I would like to add video recording in to this, which we can save data
locally and also in cloud.
Can you please help me out??
suggestions, for video uploading.

**Comment by bonoj** [comment]
Capturing screenshots of the camera preview and overlay isn't too difficult, but recording video will be trickier; I believe root access is required for screen recording below API 21. With API 21+, however, the MediaProjection class looks promising:
https://developer.android.com/reference/android/media/projection/MediaProjection.html

If you want to start by experimenting with just taking screenshots, here is a great post:
https://stackoverflow.com/questions/10296711/how-to-take-a-screenshot-and-share-it-programmatically/10296881#10296881

You'll need to add `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>` to the manifest. 

And also, because `WRITE_EXTERNAL_STORAGE` is considered a dangerous permission, you'll need to get user permission at runtime. You can add the request to the PermissionsActivity as well as the logic necessary to prevent the OverlayActivity from relaunching until the user has granted this privilege alongside the Camera and Location privileges.
